# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1e3f8433be99b95fb7fb7968e3b69b61337453395dbf5824ddc72b533241f42745ec535c55f350883941905ba4cabc67af389e3f3e3b671224b48d866e86060

test:
  secret_key_base: 5f2541a7b8612d27463b052b08ed02ba2b3ed1827be4e914ddbcf2e21ec57138c5def4ff6625baee129dbd22436d92c0185ed7388e4b76704335767e7966274f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
